<h1>Learning with <b>selected</b> data</h1>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

FEATURES = ["RR_l_0", "RR_l_0/RR_l_1", "RR_r_0", "R_val", "P_val", "signal_std"]

# 1) Load your existing 80% learning data
learn_df = pd.read_csv("original_selected_features_data/learn_valid_80.csv")  # load CSV [web:79]

# 2) If you want a validation split from the 80%: e.g., 80/20 of the 80%
X_learn = learn_df[FEATURES]
y_learn = learn_df["label"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X_learn, y_learn, test_size=0.20, random_state=42, shuffle=True, stratify=y_learn
)  # stratified split preserves balance in train/valid [web:136]

# 3) Train KNN on the training portion
knn_selected_features = KNeighborsClassifier()
knn_selected_features.fit(X_train, y_train)

# 4) Validate
y_pred = knn_selected_features.predict(X_valid)
print("Validation accuracy:", accuracy_score(y_valid, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred))
print("Classification report:\n", classification_report(y_valid, y_pred))


Validation accuracy: 0.96875
Confusion matrix:
 [[158   2]
 [  8 152]]
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.99      0.97       160
           1       0.99      0.95      0.97       160

    accuracy                           0.97       320
   macro avg       0.97      0.97      0.97       320
weighted avg       0.97      0.97      0.97       320



In [3]:
test_df  = pd.read_csv("original_selected_features_data/test_20.csv")         # load test data  [web:79]

X_test,  y_test  = test_df[FEATURES],  test_df["label"]

# 3) Evaluate on the 20% test set
y_pred = knn_selected_features.predict(X_test)
print("Test accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))

Test accuracy: 0.9475
Confusion matrix:
 [[197   3]
 [ 18 182]]
Classification report:
               precision    recall  f1-score   support

           0       0.92      0.98      0.95       200
           1       0.98      0.91      0.95       200

    accuracy                           0.95       400
   macro avg       0.95      0.95      0.95       400
weighted avg       0.95      0.95      0.95       400



<h1>Learning with <b>tsne</b> data</h1>

In [17]:
# 1) Load your existing 80% learning data
learn_df = pd.read_csv("tsne_data/learn_valid_80.csv")  # load CSV [web:79]

# 2) If you want a validation split from the 80%: e.g., 80/20 of the 80%
X_learn = learn_df[["tsne_x", "tsne_y"]]
y_learn = learn_df["label"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X_learn, y_learn, test_size=0.20, random_state=42, shuffle=True, stratify=y_learn
)  # stratified split preserves balance in train/valid [web:136]

# 3) Train KNN on the training portion
knn_tsne = KNeighborsClassifier()
knn_tsne.fit(X_train, y_train)

# 4) Validate
y_pred = knn_tsne.predict(X_valid)
print("Validation accuracy:", accuracy_score(y_valid, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred))
print("Classification report:\n", classification_report(y_valid, y_pred))

Validation accuracy: 0.9625
Confusion matrix:
 [[157   3]
 [  9 151]]
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.98      0.96       160
           1       0.98      0.94      0.96       160

    accuracy                           0.96       320
   macro avg       0.96      0.96      0.96       320
weighted avg       0.96      0.96      0.96       320



In [ ]:
test_df  = pd.read_csv("tsne_data/test_20.csv")

X_test,  y_test  = test_df[["tsne_x", "tsne_y"]],  test_df["label"]

# 3) Evaluate on the 20% test set
y_pred = knn_tsne.predict(X_test)
print("Test accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))


KeyError: ('tsne_x', 'tsne_y')

<h1>Learning with <b>all</b> data</h1>

In [6]:
learn_df = pd.read_csv("original_all_features_data/learn_valid_80.csv")  # load CSV [web:79]

# keep only numeric columns
numeric_cols = learn_df.select_dtypes(include=[np.number]).columns

# features = all numeric columns except label (in case label is numeric)
feature_cols = numeric_cols.drop("label") if "label" in numeric_cols else numeric_cols

X_learn = learn_df[feature_cols]
y_learn = learn_df["label"]

X_train, X_valid, y_train, y_valid = train_test_split(
    X_learn, y_learn, test_size=0.20, random_state=42, shuffle=True, stratify=y_learn
)


# 3) Train KNN on the training portion
knn_all_feautres = KNeighborsClassifier(n_neighbors=5, weights="distance", metric="euclidean")
knn_all_feautres.fit(X_train, y_train)

# 4) Validate
y_pred = knn_all_feautres.predict(X_valid)
print("Validation accuracy:", accuracy_score(y_valid, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred))
print("Classification report:\n", classification_report(y_valid, y_pred))


Validation accuracy: 0.9875
Confusion matrix:
 [[160   0]
 [  4 156]]
Classification report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       160
           1       1.00      0.97      0.99       160

    accuracy                           0.99       320
   macro avg       0.99      0.99      0.99       320
weighted avg       0.99      0.99      0.99       320



In [7]:
test_df  = pd.read_csv("original_all_features_data/test_20.csv")

X_test,  y_test  = test_df[feature_cols],  test_df["label"]

# 3) Evaluate on the 20% test set
y_pred = knn_all_feautres.predict(X_test)
print("Test accuracy:", accuracy_score(y_test, y_pred))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))


Test accuracy: 0.9875
Confusion matrix:
 [[200   0]
 [  5 195]]
Classification report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       200
           1       1.00      0.97      0.99       200

    accuracy                           0.99       400
   macro avg       0.99      0.99      0.99       400
weighted avg       0.99      0.99      0.99       400



<h1>Optimizing <b>all</b> data set</h1>

In [6]:
ks = [5, 15, 25]
metrics = ["euclidean", "manhattan", "cosine"]  # minkowski removed; uniform weights by default

for k in ks:
    for metric in metrics:
        knn = KNeighborsClassifier(n_neighbors=k, metric=metric)  # uniform weights (default)
        knn.fit(X_train, y_train)

        y_pred = knn.predict(X_valid)
        acc = accuracy_score(y_valid, y_pred)
        print(f"\nKNN k={k}, metric={metric}  ->  Val accuracy: {acc:.4f}")
        print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred))
        print("Classification report:\n", classification_report(y_valid, y_pred))



KNN k=5, metric=euclidean  ->  Val accuracy: 0.9875
Confusion matrix:
 [[160   0]
 [  4 156]]
Classification report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       160
           1       1.00      0.97      0.99       160

    accuracy                           0.99       320
   macro avg       0.99      0.99      0.99       320
weighted avg       0.99      0.99      0.99       320


KNN k=5, metric=manhattan  ->  Val accuracy: 0.9906
Confusion matrix:
 [[160   0]
 [  3 157]]
Classification report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       160
           1       1.00      0.98      0.99       160

    accuracy                           0.99       320
   macro avg       0.99      0.99      0.99       320
weighted avg       0.99      0.99      0.99       320


KNN k=5, metric=cosine  ->  Val accuracy: 0.9906
Confusion matrix:
 [[160   0]
 [  3 157]]
Classification r